name: benkyou
description: A new Flutter application to learn thanks to the SRS System.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  firebase_core: ^0.4.0+1
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  floor: ^0.8.0
  onesignal_flutter: ^2.0.0
  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^4.0.2
  flutter_launcher_icons:
  shared_preferences: ^0.4.2

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
#  firebase_auth: ^0.11.1+3
  cloud_firestore: any
  flutter_tts:
  path_provider: ^0.4.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_local_notifications:
  http: ^0.12.0


dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any
  floor_generator: ^0.9.0
  build_runner: ^1.6.7
  flutter_gherkin: any
  charts_flutter: ^0.8.1

#dependency_overrides:
#  image: 2.0.7

#flutter_icons:
##  image_path: "resources/icon/app_icon.png"
#  android: true
#  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - resources/imgs/favorite_empty.png
    - resources/imgs/favorite_full.png
    - resources/imgs/history.png
    - resources/imgs/home.png
    - resources/imgs/add.png
    - resources/imgs/delete.png
    - resources/imgs/translate.png
    - resources/imgs/arrow_forward.png
    - resources/imgs/arrow_forward_black.png
    - resources/imgs/arrow_backward_black.png
    - resources/imgs/waiting_cards.png
    - resources/imgs/sound.png
    - resources/imgs/profile.png
    - resources/imgs/search.png
    - resources/imgs/luffy.png
    - resources/imgs/luffy_icon.png
    - resources/imgs/side_drawer_icon.png
    - resources/imgs/mute.png
    - resources/imgs/add_photo.png
    - resources/imgs/arrow_back.png
    - resources/icon/app_icon.png
    - lib/fixtures/dev/decks.json
    - lib/fixtures/dev/cards.json
    - lib/fixtures/dev/answers.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  fonts:
     - family: Pacifico
       fonts:
         - asset: resources/fonts/Pacifico-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
