name: Flutter Integration and Unit Test

on: [push]

jobs:
  build:
    name: Launch test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.1.1
        with:
          flutter-version: '1.7.8+hotfix.4'
      - run: flutter pub get
      - run: flutter upgrade
      - run: sh launching_tests.sh
      - run: flutter test